# Introduction to NumPy

NumPy is one of the two most important libraries in Python for data science, along with Pandas. NumPy is a crucial library for effectively loading, storing, and manipulating in-memory data in Python, all of which will be at the heart of what you do with data science in Python.

Datasets come from a huge range of sources and in a wide range of formats, such as text documents, images, sound clips, numerical measurements, and nearly anything else. Despite this variety, however, the start of data science is to think of all data fundamentally as arrays of numbers.

For example, the words in documents can be represented as the numbers that encode letters in computers or even the frequency of particular words in a collection of documents. Digital images can be thought of as two-dimensional arrays of numbers representing pixel brightness or color. Sound files can be represented as one-dimensional arrays of frequency versus time. However, no matter what form our data takes, in order to analyze it, our first step will be to transform it into arrays of numbers—which is where NumPy comes in (and pandas down the road).

NumPy is short for *Numerical Python*, and it provides an efficient means of storing and operating on dense data buffers in Python. Array-oriented computing in Python goes back to 1995 with the Numeric library. Scientific programming in Python took off over the next 10 years, but the collections of libraries splintered. The NumPy project began in 2005 as a means of bringing the Numeric and NumArray projects together around a single array-based framework.

Some examples in this section are drawn from the *Python Data Science Handbook* by Jake VanderPlas (content available [on GitHub](https://github.com/jakevdp/PythonDataScienceHandbook)) and *Python for Data Analysis* by Wes McKinney. Text from the *Python Data Science Handbook* is released under the [CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode); code is released under the [MIT license](https://opensource.org/licenses/MIT).

Let's get started exploring NumPy! Our first step will be to import NumPy using `np` as an alias:

In [1]:
import numpy as np

Get used to this convention — it's a common convention in Python, and it's the way we will use and refer to NumPy throughout the rest of this course.

## Built-In Help

There's a lot to learn about NumPy, and it can be tough to remember it all the first time through. Don't worry! IPython — the underlying program that enables notebooks like this one to interact with Python—has you covered.

First off, IPython gives you the ability to quickly explore the contents of a package like NumPy by using the tab-completion feature. So, if you want to see all of the functions available with NumPy, type this:

```ipython
In [2]: np.<TAB>
```
When you do so, a drop-down menu will appear next to the `np.`

### Exercise

In [148]:
# Place your cursor after the period and press <TAB>:
np.add

<ufunc 'add'>

From the drop-down menu, you can select any function to run. Better still, you can select any function and view the built-in help documentation for it. For example, to view the documentation for the NumPy `add()` function, you can run this code:

```ipython
In [3]: np.add?
```
Try this with a few different functions. Remember, these functions are just like ones you wrote in Section 2; the documentation will help explain what parameters you can (or should) provide the function, in addition to what output you can expect.

### Exercise

In [4]:
# Replace 'add' below with a few different NumPy function names and look over the documentation:
np.add?

Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            d:\users\aksha\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the 

For more detailed documentation (along with additional tutorials and other resources), visit [www.numpy.org](http://www.numpy.org).

Now that you know how to quickly get help while you are working on your own, let's return to storing data in arrays.

## NumPy arrays: a specialized data structure for analysis

> **Learning goal:** By the end of this subsection, you should have a basic understanding of what NumPy arrays are and how they differ from the other Python data structures you have studied thus far.

We started the discussion in this section by noting that data science starts by representing data as arrays of numbers.

"Wait!" you might be thinking. "Can't we just use Python lists for that?"

Depending on the data, yes, you could (and you will use lists as a part of working with data in Python). But to see what we might want to use a specialized data structure for, let's look a little more closely at lists.

### Lists in Python

Python lists can hold just one kind of object. Let's use one to create a list of just integers:

In [5]:
myList = list(range(10))
myList

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Remember list comprehension? We can use it to probe the data types of items in a list:

In [6]:
[type(item) for item in myList]

[int, int, int, int, int, int, int, int, int, int]

Of course, a really handy feature of Python lists is that they can hold heterogeneous types of data in a single list object:

In [7]:
myList2 = [True, "2", 3.0, 4]
[type(item) for item in myList2]

[bool, str, float, int]

However, this flexibility comes at a price. Each item in a list is really a separate Python object (the list is an object itself, true, but mostly it is an object that serves as a container for the memory pointers to the constituent objects). That means that each item in a list must contain its own type info, reference count, and other information. All of this information can become expensive in terms of memory and performance if we are dealing with hundreds of thousands or millions of items in a list. Moreover, for many uses in data science, our arrays just store a single type of data (such as integers or floats), which means that all of the object-related information for items in such an array would be redundant. It can be much more efficient to store data in a fixed-type array.

<img align="left" style="padding-right:10px;" src="https://raw.githubusercontent.com/microsoft/computerscience/master/Educator%20Resources/Reactor%20Workshops/Data%20Science/Track%201/Graphics/Sec3_array_vs_list.png">

Enter the fixed-type, NumPy-style array.

### Fixed-type arrays in Python

At the level of implementation by the computer, the `ndarray` that is part of the NumPy package contains a single pointer to one contiguous block of data. This is efficient memory-wise and computationally. Better still, NumPy provides efficient *operations* on data stored in `ndarray` objects.

(Note that we will pretty much use “array,” “NumPy array,” and “ndarray” interchangeably throughout this section to refer to the ndarray object.)

#### Creating NumPy arrays method 1: using Python lists

There are multiple ways to create arrays in NumPy. Let's start by using our good old familiar Python lists. We will use the `np.array()` function to do this (remember, we imported NumPy as '`np`'):

In [8]:
# Create an integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Remember that, unlike Python lists, NumPy constrains arrays to contain a single type. So, if data types fed into a NumPy array do not match, NumPy will attempt to *upcast* them if possible. To see what we mean, here NumPy upcasts integers to floats:

In [9]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

### Exercise

In [10]:
# What happens if you construct an array using a list that contains a combination of integers, floats, and strings?


If you want to explicitly set the data type of your array when you create it, you can use the `dtype` keyword:

In [11]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

### Exercise

In [12]:
# Try this using a different dtype.
# Remember that you can always refer to the documentation with the command np.array.


Most usefully for a lot of applications in data science, NumPy arrays can explicitly be multidimensional (like matrices or tensors). Here's one way of creating a multidimensional array using a list of lists:

In [13]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The inner lists in a list of lists are treated as rows of the two-dimensional array you created.

#### Creating NumPy arrays method 2: building from scratch

In practice, it is often more efficient to create arrays from scratch using functions built into NumPy, particularly for larger arrays. Here are a few examples; these example will help introduce you to several useful NumPy functions.

In [14]:
# Create an integer array of length 10 filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Create a 3x5 array filled with 3.14
# The first number in the tuple gives the number of rows
# The second number in the tuple sets the number of columns
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in Python range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [149]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.4140381 , 0.15624294, 0.40573172],
       [0.3907542 , 0.97588901, 0.6109771 ],
       [0.55331641, 0.73247161, 0.82328988]])

array([[-1.37788947, -0.78366533,  1.43697256],
       [ 0.38360914, -0.75570442, -2.5250003 ],
       [-0.76358443,  1.7420311 , -0.42097296]])

In [21]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 0, 0],
       [1, 8, 4],
       [6, 8, 2]])

In [22]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

Now take a couple of minutes to go back and play with these code snippets, changing the parameters. These functions are the bread-and-butter of creating NumPy arrays and you will want to become comfortable with them.

Below is a table listing out several of the array-creation functions in NumPy.

| Function      | Description |
|:--------------|:------------|
| `array`       | Converts input data (list, tuple, array, or other sequence type) to an ndarray either |
|               | by inferring a dtype or explicitly specifying a dtype. Copies the input data by default. |
| `asarray`     | Converts input to ndarray, but does not copy if the input is already an ndarray. |
| `arange`      | Similar to the built-in `range()` function but returns an ndarray instead of a list. |
| `ones`, `ones_like` | Produces an array of all 1s with the given shape and dtype. |
|               | `ones_like` takes another array and produces a ones-array of the same shape and dtype. |
| `zeros`, `zeros_like` | Similar to `ones` and `ones_like` but producing arrays of 0s instead. |
| `empty`, `empty_like` | Creates new arrays by allocating new memory, but does not populate with any values 
|               | like `ones` and `zeros`. |
| `full`, `full_like` | Produces an array of the given shape and dtype with all values set to the indicated “fill value.” |
|               | `full_like` takes another array and produces a a filled array of the same shape and dtype. |
| `eye`, `identity` | Create a square $N \times N$ identity matrix (1s on the diagonal and 0s elsewhere) |

### NumPy data types

The standard NumPy data types are listed in the following table. Note that when constructing an array, they can be specified using a string:

```python
np.zeros(8, dtype='int16')
```

Or they can be specified directly using the NumPy object:

```python
np.zeros(8, dtype=np.int16)
```

| Data type	    | Description |
|:--------------|:------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

If these data types seem a lot like those in C, that's because NumPy is built in C.

> **Takeaway:** NumPy arrays are a data structure similar to Python lists that provide high performance when storing and working on large amounts of homogeneous data—precisely the kind of data that you will encounter frequently in doing data science. NumPy arrays support many data types beyond those discussed in this course. With all of that said, however, don’t worry about memorizing all of the NumPy dtypes. **It’s often just necessary to care about the general kind of data you’re dealing with: floating point, integer, Boolean, string, or general Python object.**

## Working with NumPy arrays: the basics

> **Learning goal:** By the end of this subsection, you should be comfortable working with NumPy arrays in basic ways.

Now that you know how to create arrays in NumPy, you need to get comfortable manipulating them for two reasons. First, you will work with NumPy arrays as part of your exploration of data science. Second, our other important Python data-science tool, pandas, is actually built around NumPy. Getting good at working with NumPy arrays will pay dividends in the next section (Section 4) and beyond: NumPy arrays are the building blocks for the `Series` and `DataFrame` data structures in the Python pandas library and you will use them *a lot* in data science. To get comfortable with array manipulation, we will cover five specifics:
- **Arrays attributes**: Assessing the size, shape, and data types of arrays
- **Indexing arrays**: Getting and setting the value of individual array elements
- **Slicing arrays**: Getting and setting smaller subarrays within a larger array
- **Reshaping arrays**: Changing the shape of a given array
- **Joining and splitting arrays**: Combining multiple arrays into one and splitting one array into multiple arrays

### Array attributes
First, let's look at some array attributes. We'll start by defining three arrays filled with random numbers: one one-dimensional, another two-dimensional, and the last three-dimensional. Because we will be using NumPy's random number generator, we will set a *seed* value in order to ensure that you get the same random arrays each time you run this code:

In [150]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

a1 = np.random.randint(10, size=6)  # One-dimensional array
a2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
a3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ``ndim`` (the number of dimensions of an array), ``shape`` (the size of each dimension of an array), and ``size`` (the total number of elements in an array).

### Exercise:

In [152]:
# Change the values in this code snippet to look at the attributes for a1, a2, and a3:
print("a3 ndim: ", a3.ndim)
print("a3 shape:", a3.shape)
print("a3 size: ", a3.size)

a3 ndim:  3
a3 shape: (3, 4, 5)
a3 size:  60


Another useful array attribute is the `dtype`, which we already encountered earlier in this section as a means of determining the type of data in an array:

In [26]:
print("dtype:", a3.dtype)

dtype: int32


### Exercise:

In [27]:
# Explore the dtype for the other arrays.
# What dtypes do you predict them to have?
print("dtype:", a3.dtype)

dtype: int32


### Indexing arrays

Indexing in NumPy is pretty similar to indexing lists in standard Python. In fact, indices in one-dimensional arrays work exactly as they do with Python lists:

In [28]:
a1

array([5, 0, 3, 3, 7, 9])

In [29]:
a1[0]

5

In [30]:
a1[4]

7

As with regular Python lists, in order to index from the end of the array, you can use negative indices:

In [31]:
a1[-1]

9

In [32]:
a1[-2]

7

### Exercise:

In [33]:
# Do multidimensional NumPy arrays work like Python lists of lists?
# Try a few combinations like a2[1][1] or a3[0][2][1] and see what comes back


You might have noticed that we can treat multidimensional arrays like lists of lists. But a more common means of accessing items in multidimensional arrays is to use a comma-separated tuple of indices.

(Yes, we realize that these comma-separated tuples use square brackets rather than the parentheses the name might suggest, but they are nevertheless referred to as tuples.)

In [34]:
a2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
a2[0, 0]

3

In [36]:
a2[2, 0]

1

In [37]:
a2[2, -1]

7

You can also modify values by use of this same comma-separated index notation:

In [38]:
a2[0, 0] = 12
a2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Remember, once defined, NumPy arrays have a fixed data type. So, if you attempt to insert a float into an integer array, the value will be silently truncated.

In [39]:
a1[0] = 3.14159
a1

array([3, 0, 3, 3, 7, 9])

### Exercise:

In [40]:
# What happens if you try to insert a string into a1?
# Hint: try both a string like '3' and one like 'three'


### Slicing arrays
Similar to how you can use square brackets to access individual array elements, you can also use them to access subarrays. You do this with the *slice* notation, marked by the colon (`:`) character. NumPy slicing syntax follows that of the standard Python list; so, to access a slice of an array `a`, use this notation:
``` python
a[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
Let's take a look at accessing sub-arrays in one dimension and in multiple dimensions.

#### One-dimensional slices

In [41]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [43]:
a[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [44]:
a[4:7]  # middle sub-array

array([4, 5, 6])

In [45]:
a[::2]  # every other element

array([0, 2, 4, 6, 8])

In [46]:
a[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

### Exercise:

In [47]:
# How would you access the *last* five elements of array a?
# How about every other element of the last five elements of a?
# Hint: Think back to list indexing in Python


Be careful when using negative values for ``step``. When ``step`` has a negative value, the defaults for ``start`` and ``stop`` are swapped and you can use this functionality to reverse an array:

In [48]:
a[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [49]:
a[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### Exercise:

In [50]:
# How can you create a slice that contains every third element of a
# descending from the second-to-last element to the second element of a?


#### Multidimensional slices

Multidimensional slices use the same slice notation of one-dimensional subarrays mixed with the comma-separated notation of multidimensional arrays. Some examples will help illustrate this.

In [51]:
a2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [52]:
a2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [53]:
a2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [54]:
a2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

### Exercise:

In [55]:
# Now try to show 2 rows and 4 columns with every other element?


#### Accessing array rows and columns
One thing you will often need to do in manipulating data is accessing a single row or column in an array. You can do this through a combination of indexing and slicing; specifically by using an empty slice marked by a single colon (``:``). Again, some examples will help illustrate this.

In [56]:
print(a2[:, 0])  # first column of x2

[12  7  1]


In [57]:
print(a2[0, :])  # first row of x2

[12  5  2  4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [58]:
print(a2[0])  # equivalent to a2[0, :]

[12  5  2  4]


### Exercise:

In [59]:
# How would you access the third column of a3?
# How about the third row of a3?


#### Slices are no-copy views
It's important to know that slicing produces *views* of array data, not *copies*. This is a **huge** difference between NumPy array slicing and Python list slicing. With Python lists, slices are only shallow copies of lists; if you modify a copy, it doesn't affect the parent list. When you modify a NumPy subarray, you modify the original list. Be careful: this can have ramifications when you are trying to just work with a small part of a large dataset and you don’t want to change the whole thing. Let's look more closely.

In [60]:
print(a2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Extract a $2 \times 2$ subarray from `a2`:

In [61]:
a2_sub = a2[:2, :2]
print(a2_sub)

[[12  5]
 [ 7  6]]


Now modify this subarray:

In [62]:
a2_sub[0, 0] = 99
print(a2_sub)

[[99  5]
 [ 7  6]]


`a2` is now modified as well:

In [63]:
print(a2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Exercise:

In [64]:
# Now try reversing the column and row order of a2_sub
# Does a2 look the way you expected it would after that manipulation?


The fact that slicing produces views rather than copies is useful for data-science work. As you work with large datasets, you will often find that it is easier to access and manipulate pieces of those datasets rather than copying them entirely.

#### Copying arrays
Instead of just creating views, sometimes it is necessary to copy the data in one array to another. When you need to do this, use the `copy()` method:

In [65]:
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [66]:
a2_sub_copy[0, 0] = 42
print(a2_sub_copy)

[[42  5]
 [ 7  6]]


In [67]:
print(a2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping arrays
Another way in which you will need to manipulate arrays is by reshaping them. This involves changing the number and size of dimensions of an array. This kind of manipulation can be important in getting your data to meet the expectations of machine learning programs or APIs.

The most flexible way of doing this kind of manipulation is with the `reshape` method. For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [68]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Another common manipulation you will do in data science is converting one-dimensional arrays into two-dimensional row or column matrices. This can be a common necessity when doing linear algebra for machine learning. While you can do this by means of the `reshape` method, an easier way is to use the `newaxis` keyword in a slice operation:

In [69]:
a = np.array([1, 2, 3])

# row vector via reshape
a.reshape((1, 3))

array([[1, 2, 3]])

In [70]:
# row vector via newaxis
a[np.newaxis, :]

array([[1, 2, 3]])

In [71]:
# column vector via reshape
a.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [72]:
# column vector via newaxis
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

You will see this type of transformation a lot in the remainder of this course.

### Joining and splitting arrays

Another common data-manipulation need in data science is combining multiple datasets; learning first how to do this with NumPy arrays will help you in the next section (Section 4) when we do this with more complex data structures. You will many times also need to split a single array into multiple arrays.

#### Joining arrays
To join arrays in NumPy, you will most often use `np.concatenate`, which is the method we will cover here. If you find yourself in the future needing to specifically join arrays in mixed dimensions (a rarer case), read the documentation on `np.vstack`, `np.hstack`, and `np.dstack`.

##### `np.concatenate()`

`np.concatenate` takes a tuple or list of arrays as its first argument:

In [73]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])
np.concatenate([a, b])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [74]:
c = [99, 99, 99]
print(np.concatenate([a, b, c]))

[ 1  2  3  3  2  1 99 99 99]


`np.concatenate` can also be used for two-dimensional arrays:

In [75]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [76]:
# concatenate along the first axis, which is the default
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

### Exercise:

In [77]:
# Recall that axes are zero-indexed in NumPy.
# What do you predict np.concatenate([grid, grid], axis=1) will produce?


#### Splitting arrays
In order to split arrays into multiple smaller arrays, you can use the functions ``np.split``, ``np.hsplit``, ``np.vsplit``, and ``np.dsplit``.  As above, we will only cover the most commonly used function (`np.split`) in this course.

##### `np.split()`
Let's first examine the case of a one-dimensional array:

In [78]:
a = [1, 2, 3, 99, 99, 3, 2, 1]
a1, a2, a3 = np.split(a, [3, 5])
print(a1, a2, a3)

[1 2 3] [99 99] [3 2 1]


Notice that *N* split-points produces to *N + 1* subarrays. In this case it has formed the subarray `a2` with `a[3]` and `a[4]` (the element just before position 5 [remember how Python indexing goes], the second input in the tuple) as elements. `a1` and `a3` pick up the leftover portions from the original array `a`.

### Exercise:

In [79]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
# What does np.split(grid, [1, 2]) produce?
# What about np.split(grid, [1, 2], axis=1)?


> **Takeaway:** Manipulating datasets is a fundamental part of preparing data for analysis. The skills you learned and practiced here will form building blocks for the most sophisticated data-manipulation you will learn in later sections in this course.

## Fancy indexing

So far, we have explored how to access and modify portions of arrays using simple indices like `arr[0]`) and slices like `arr[:5]`. Now it is time for fancy indexing, in which we pass an array of indices to an array in order to access or modify multiple array elements at the same time.

Let's try it out:

In [81]:
rand = np.random.RandomState(42)

arr = rand.randint(100, size=10)
print(arr)

[51 92 14 71 60 20 82 86 74 74]


Suppose you need to access three different elements. Using the tools you currently have, your code might look something like this:

In [82]:
[arr[3], arr[7], arr[2]]

[71, 86, 14]

With fancy indexing, you can pass a single list or array of indices to do the same thing:

In [83]:
ind = [3, 7, 4]
arr[ind]

array([71, 86, 60])

Another useful aspect of fancy indexing is that the shape of the output array reflects the shape of the *index arrays* you supply, rather than the shape of the array you are accessing. This is handy because there will be many times in a data scientist's life when they want to grab data from an array in a particular manner, such as to pass it to a machine learning API. Let's examine this property with an example:

In [84]:
ind = np.array([[3, 7],
                [4, 5]])
arr[ind]

array([[71, 86],
       [60, 20]])

`arr` is a one-dimensional array, but `ind`, your index array, is a $2 \times 2$ array, and that is the shape the results comes back in.

### Exercise:

In [85]:
# What happens when your index array is bigger than the target array?
# Hint: you could use a large one-dimensional array or something fancier like ind = np.arange(0, 12).reshape((6, 2))


Fancy indexing also works in multiple dimensions:

In [86]:
arr2 = np.arange(12).reshape((3, 4))
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

As with standard indexing, the first index refers to the row and the second to the column:

In [87]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
arr2[row, col]

array([ 2,  5, 11])

What did you actually get as your final result here? The first value in the result array is `arr2[0, 2]`, the second one is `arr2[1, 1]`, and the third one is `arr2[2, 3]`.

The pairing of indices in fancy indexing follows all the same broadcasting rules we covered earlier. Thus, if you combine a column vector and a row vector within the indices, you get a two-dimensional result:

In [88]:
arr2[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

Here, each row value is matched with each column vector, exactly as we saw in broadcasting of arithmetic operations.

### Exercise:

In [89]:
# Now try broadcasting this on your own.
# What do you get with row[:, np.newaxis] * col? 
# Or row[:, np.newaxis] * row? col[:, np.newaxis] * row?
# What about col[:, np.newaxis] * row?
# Hint: think back to the broadcast rules


**The big takeaway:** It is always important to remember that fancy indexing returns values reflected by the *broadcasted shape of the indices*, and not the shape of the array being indexed.

### Combined indexing

You can also combine fancy indexing with the other indexing schemes you have learned. Consider `arr2` again:

In [90]:
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Now combine fancy and simple indices:

In [91]:
arr2[2, [2, 0, 1]]

array([10,  8,  9])

What did you get back? The elements at positions 2, 0, and 1 of row 2 (the third row).

You can also combine fancy indexing with slicing:

In [92]:
arr2[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

### Modifying values using fancy indexing

Fancy indexing is, of course, not just for accessing parts of an array, but also for modifying parts of an array:

In [94]:
ind = np.arange(10)
arr = np.array([2, 1, 8, 4])
ind[arr] = 99
print(ind)

[ 0 99 99  3 99  5  6  7 99  9]


You can also use a ufunc here and subtract 10 from each element of the array:

In [95]:
ind[arr] -= 10
print(ind)

[ 0 89 89  3 89  5  6  7 89  9]


Be cautious when using repeated indices with operations like these. They might not always produce the results you expect. For example:

In [156]:
ind = np.zeros(10)
ind[[0, 0]] = [4]
print(ind)

[4. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Where did the 4 go? The result of this operation is to first assign `ind[0] = 4`, followed by `ind[0] = 6`. So the result is that `ind[0]` contains the value 6.

But not every operation repeats the way you might think it should:

In [155]:
arr = [2, 3, 3, 4, 4, 4]
ind[arr] += 1
ind

array([4., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

We might have expected that `ind[3]` would contain the value 2 and `ind[4]` would contain the value 3. After all, that is how many times each index is repeated. So what happened?

This happened because `ind[arr] += 1` is really shorthand for `ind[arr] = ind[arr] + 1`. `ind[arr] + 1` is evaluated, and then the result is assigned to the indices in `ind`. So, similar to the previous example, this is not augmentation that happens multiple times, but an assignment, which can lead to potentially counterintuitive results.



[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


### Exercise:

In [99]:
# What does np.subtract.at(ind, arr, 1) give you?
# Play around with some of the other ufuncs we have seen.


> **Takeaway:** Fancy indexing enables you to select and manipulate several array members at once. This type of programmatic data manipulation is common in data science: often what you want to do with your data you want to do on several data points at once.

## Sorting arrays

So far we have just worried about accessing and modifying NumPy arrays. Another huge thing you will need to do as a data scientist is sort array data. Sorting is often an important means of teasing out the structure in data (such as outlying data points).

Although you could use Python's built-in `sort` and `sorted` functions, they will not work nearly as efficiently as NumPy's `np.sort` function.

`np.sort` returns a sorted version of an array without modifying the input:

In [100]:
a = np.array([2, 1, 4, 3, 5])
np.sort(a)

array([1, 2, 3, 4, 5])

In order to sort the array in-place, use the `sort` method directly on arrays:

In [101]:
a.sort()
print(a)

[1 2 3 4 5]


A related function is `argsort`, which returns the *indices* of the sorted elements rather than the elements themselves:

In [102]:
a = np.array([2, 1, 4, 3, 5])
b = np.argsort(a)
print(b)

[1 0 3 2 4]


The first element of this result gives the index of the smallest element, the second value gives the index of the second smallest, and so on. These indices can then be used (via fancy indexing) to reconstruct the sorted array:

In [103]:
a[b]

array([1, 2, 3, 4, 5])

### Sorting along rows or columns

A useful feature of NumPy's sorting algorithms is the ability to sort along specific rows or columns of a multidimensional array using the `axis` argument. For example:

In [104]:
rand = np.random.RandomState(42)
table = rand.randint(0, 10, (4, 6))
print(table)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [105]:
# Sort each column of the table
np.sort(table, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [106]:
# Sort each row of the table
np.sort(table, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

Bear in mind that this treats each row or column as an independent array; any relationships between the row or column values will be lost doing this kind of sorting.

## Partial sorting: partitioning

Sometimes you don't need to sort an entire array, you just need to find the *k* smallest values in the array (often when looking at the distance of data points from one another). NumPy supplies this functionality through the `np.partition` function. `np.partition` takes an array and a number *k*; the result is a new array with the smallest *k* values to the left of the partition, and the remaining values to the right (in arbitrary order):

In [107]:
arr = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(arr, 3)

array([2, 1, 3, 4, 6, 5, 7])

Note that the first three values in the resulting array are the three smallest in the array, and the remaining array positions contain the remaining values. Within the two partitions, the elements have arbitrary order.

Similarly to sorting, we can partition along an arbitrary axis of a multidimensional array:

In [108]:
np.partition(table, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

The result is an array where the first two slots in each row contain the smallest values from that row, with the remaining values filling the remaining slots.

Finally, just as there is an `np.argsort` that computes indices of the sort, there is an `np.argpartition` that computes indices of the partition. We'll see this in action in the following section when we discuss pandas.

> **Takeaway:** Sorting your data is a fundamental means of exploring it and answering questions about it. The sorting algorithms in NumPy provide you with a fast, computationally efficient way of doing this on large amounts of data and with fine-grain control.

In [112]:
a = np.arange(4)
print("a     =", a)
print("a + 5 =", a + 5)
print("a - 5 =", a - 5)
print("a * 2 =", a * 2)
print("a / 2 =", a / 2)
print("a // 2 =", a // 2)  # floor division

a     = [0 1 2 3]
a + 5 = [5 6 7 8]
a - 5 = [-5 -4 -3 -2]
a * 2 = [0 2 4 6]
a / 2 = [0.  0.5 1.  1.5]
a // 2 = [0 0 1 1]


There are also ufuncs for negation, exponentiation, and the modulo operation:

In [113]:
print("-a     = ", -a)
print("a ** 2 = ", a ** 2)
print("a % 2  = ", a % 2)

-a     =  [ 0 -1 -2 -3]
a ** 2 =  [0 1 4 9]
a % 2  =  [0 1 0 1]


You can also combine these ufuncs using the standard order of operations:

In [114]:
-(0.5*a + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

The Python operators are not actually the ufuncs, but are rather wrappers around functions built into NumPy. So the `+` operator is actually a wrapper for the `add` function:

In [115]:
np.add(a, 2)

array([2, 3, 4, 5])

Here is a cheat sheet for the equivalencies between Python operators and NumPy ufuncs:

| Operator	    | Equivalent ufunc    | Description                           |
|:--------------|:--------------------|:--------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

Python Boolean operators also work; we will explore those later in this section.

#### Absolute value

NumPy also understands Python's built-in absolute value function:

In [116]:
a = np.array([-2, -1, 0, 1, 2])
abs(a)

array([2, 1, 0, 1, 2])

This corresponds to the NumPy ufunc `np.absolute` (which is also available under the alias `np.abs`):

In [117]:
np.absolute(a)

array([2, 1, 0, 1, 2])

In [118]:
np.abs(a)

array([2, 1, 0, 1, 2])

#### Exponents and logarithms

You will need to use exponents and logarithms a lot in data science; these are some of the most common data transformations for machine learning and statistical work.

In [119]:
a = [1, 2, 3]
print("a     =", a)
print("e^a   =", np.exp(a))
print("2^a   =", np.exp2(a))
print("3^a   =", np.power(3, a))

a     = [1, 2, 3]
e^a   = [ 2.71828183  7.3890561  20.08553692]
2^a   = [2. 4. 8.]
3^a   = [ 3  9 27]


The basic `np.log` gives the natural logarithm; if you need to compute base-2 or base-10 logarithms, NumPy also provides those:

In [120]:
a = [1, 2, 4, 10]
print("a        =", a)
print("ln(a)    =", np.log(a))
print("log2(a)  =", np.log2(a))
print("log10(a) =", np.log10(a))

a        = [1, 2, 4, 10]
ln(a)    = [0.         0.69314718 1.38629436 2.30258509]
log2(a)  = [0.         1.         2.         3.32192809]
log10(a) = [0.         0.30103    0.60205999 1.        ]


There are also some specialized versions of these ufuncs to help maintain precision when dealing with very small inputs:

In [121]:
a = [0, 0.001, 0.01, 0.1]
print("exp(a) - 1 =", np.expm1(a))
print("log(1 + a) =", np.log1p(a))

exp(a) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + a) = [0.         0.0009995  0.00995033 0.09531018]


These functions give more precise values than if you were to use the raw `np.log` or `np.exp` on very small values of `a`.

gamma(a)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(a)| = [ 0.          3.17805383 12.80182748]
beta(a, 2)   = [0.5        0.03333333 0.00909091]


## Aggregations

> **Learning goal:** By the end of this subsection, you should be comfortable aggregating data in NumPy.

One of the first things you will find yourself doing with most datasets is computing the summary statistics for the data in order to get a general overview of your data before exploring it further. These summary statistics include the mean and standard deviation, in addition to other aggregates, such as the sum, product, median, minimum and maximum, or quantiles of the data.

NumPy has fast built-in aggregation functions for working on arrays that are the subject of this sub-section.

### Summing the values of an array

You can use the built-in Python `sum` function to sum up the values in an array.

In [124]:
import numpy as np

In [125]:
myList = np.random.random(100)
sum(myList)

50.461758453195614

If you guessed that there is also a built-in NumPy function for this, you guessed correctly:

In [126]:
np.sum(myList)

50.46175845319564

And if you guessed that the NumPy version is faster, you are doubly correct:

In [127]:
large_array = np.random.rand(1000000)
%timeit sum(large_array)
%timeit np.sum(large_array)

81.8 ms ± 562 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
692 µs ± 4.29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


For all their similarity, bear in mind that `sum` and `np.sum` are not identical; their optional arguments have different meanings, and `np.sum` is aware of multiple array dimensions.

### Minimum and maximum

Just as Python has built-in `min` and `max` functions, NumPy has similar, vectorized versions:

In [128]:
np.min(large_array), np.max(large_array)

(7.071203171893359e-07, 0.9999997207656334)

You can also use `min`, `max`, and `sum` (and several other NumPy aggregates) as methods of the array object itself:

In [129]:
print(large_array.min(), large_array.max(), large_array.sum())

7.071203171893359e-07 0.9999997207656334 500216.8034810001


### Multidimensional aggregates

Because you will often treat the rows and columns of two-dimensional arrays differently (treating columns as variables and rows as observations of those variables, for example), it can often be desirable to aggregate array data along a row or column. Let's consider a two-dimensional array:

In [130]:
md = np.random.random((3, 4))
print(md)

[[0.79832448 0.44923861 0.95274259 0.03193135]
 [0.18441813 0.71417358 0.76371195 0.11957117]
 [0.37578601 0.11936151 0.37497044 0.22944653]]


Unless you specify otherwise, each NumPy aggregation function will compute the aggregate for the entire array. Hence:

In [131]:
md.sum()

5.1136763453287335

Aggregation functions take an additional argument specifying the *axis* along which to compute the aggregation. For example, we can find the minimum value within each column by specifying `axis=0`:

In [132]:
md.min(axis=0)

array([0.18441813, 0.11936151, 0.37497044, 0.03193135])

### Exercise:

In [133]:
# What do you get when you try md.max(axis=1)?


Remember that the `axis` keyword specifies the *dimension of the array that is to be collapsed*, not the dimension that will be returned. Thus specifying `axis=0` means that the first axis will be the one collapsed: for two-dimensional arrays, this means that values within each column will be aggregated.

### Other aggregation functions

The table below lists other aggregation functions in NumPy. Most NumPy aggregates have a '`NaN`-safe' version, which computes the result while ignoring missing values marked by the `NaN` value.

|Function Name      |   NaN-safe Version  | Description                                   |
|:------------------|:--------------------|:----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

We will see these aggregates often throughout the rest of the course.

> **Takeaway:** Aggregation is the primary means you will use to explore you data, not just when using NumPy, but particularly in conjunction with pandas, the Python library you will learn about in the next section, which builds off of NumPy and thus off of everything you have learned thus far.